// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/vicanso/cybertect/ent"
)

// The ConfigurationFunc type is an adapter to allow the use of ordinary
// function as Configuration mutator.
type ConfigurationFunc func(context.Context, *ent.ConfigurationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ConfigurationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ConfigurationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ConfigurationMutation", m)
}

// The DNSDetectorFunc type is an adapter to allow the use of ordinary
// function as DNSDetector mutator.
type DNSDetectorFunc func(context.Context, *ent.DNSDetectorMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f DNSDetectorFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.DNSDetectorMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.DNSDetectorMutation", m)
}

// The DNSDetectorResultFunc type is an adapter to allow the use of ordinary
// function as DNSDetectorResult mutator.
type DNSDetectorResultFunc func(context.Context, *ent.DNSDetectorResultMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f DNSDetectorResultFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.DNSDetectorResultMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.DNSDetectorResultMutation", m)
}

// The DatabaseDetectorFunc type is an adapter to allow the use of ordinary
// function as DatabaseDetector mutator.
type DatabaseDetectorFunc func(context.Context, *ent.DatabaseDetectorMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f DatabaseDetectorFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.DatabaseDetectorMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.DatabaseDetectorMutation", m)
}

// The DatabaseDetectorResultFunc type is an adapter to allow the use of ordinary
// function as DatabaseDetectorResult mutator.
type DatabaseDetectorResultFunc func(context.Context, *ent.DatabaseDetectorResultMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f DatabaseDetectorResultFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.DatabaseDetectorResultMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.DatabaseDetectorResultMutation", m)
}

// The HTTPDetectorFunc type is an adapter to allow the use of ordinary
// function as HTTPDetector mutator.
type HTTPDetectorFunc func(context.Context, *ent.HTTPDetectorMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f HTTPDetectorFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.HTTPDetectorMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.HTTPDetectorMutation", m)
}

// The HTTPDetectorResultFunc type is an adapter to allow the use of ordinary
// function as HTTPDetectorResult mutator.
type HTTPDetectorResultFunc func(context.Context, *ent.HTTPDetectorResultMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f HTTPDetectorResultFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.HTTPDetectorResultMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.HTTPDetectorResultMutation", m)
}

// The PingDetectorFunc type is an adapter to allow the use of ordinary
// function as PingDetector mutator.
type PingDetectorFunc func(context.Context, *ent.PingDetectorMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PingDetectorFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PingDetectorMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PingDetectorMutation", m)
}

// The PingDetectorResultFunc type is an adapter to allow the use of ordinary
// function as PingDetectorResult mutator.
type PingDetectorResultFunc func(context.Context, *ent.PingDetectorResultMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PingDetectorResultFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PingDetectorResultMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PingDetectorResultMutation", m)
}

// The TCPDetectorFunc type is an adapter to allow the use of ordinary
// function as TCPDetector mutator.
type TCPDetectorFunc func(context.Context, *ent.TCPDetectorMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TCPDetectorFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TCPDetectorMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TCPDetectorMutation", m)
}

// The TCPDetectorResultFunc type is an adapter to allow the use of ordinary
// function as TCPDetectorResult mutator.
type TCPDetectorResultFunc func(context.Context, *ent.TCPDetectorResultMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TCPDetectorResultFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TCPDetectorResultMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TCPDetectorResultMutation", m)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *ent.UserMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserMutation", m)
}

// The UserLoginFunc type is an adapter to allow the use of ordinary
// function as UserLogin mutator.
type UserLoginFunc func(context.Context, *ent.UserLoginMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserLoginFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserLoginMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserLoginMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, ent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op ent.Op) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk ent.Hook, cond Condition) ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, ent.Delete|ent.Create)
func On(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, ent.Update|ent.UpdateOne)
func Unless(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) ent.Hook {
	return func(ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(context.Context, ent.Mutation) (ent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []ent.Hook {
//		return []ent.Hook{
//			Reject(ent.Delete|ent.Update),
//		}
//	}
func Reject(op ent.Op) ent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []ent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...ent.Hook) Chain {
	return Chain{append([]ent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() ent.Hook {
	return func(mutator ent.Mutator) ent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...ent.Hook) Chain {
	newHooks := make([]ent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
