export const USERS_ME = '/users/v1/me'
export const USERS_LOGIN = '/users/v1/me/login'
export const USERS_LOGOUT = '/users/v1/me/logout'
export const USERS = '/users/v1'
export const COMMONS_CAPTCHA = '/commons/captcha'
export const DETECTORS = '/detectors/v1/:category'
export const DETECTOR = '/detectors/v1/:category/:id'
