// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vicanso/cybertect/ent/databasedetectorresult"
	"github.com/vicanso/cybertect/ent/predicate"
)

// DatabaseDetectorResultQuery is the builder for querying DatabaseDetectorResult entities.
type DatabaseDetectorResultQuery struct {
	config
	ctx        *QueryContext
	order      []databasedetectorresult.OrderOption
	inters     []Interceptor
	predicates []predicate.DatabaseDetectorResult
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DatabaseDetectorResultQuery builder.
func (ddrq *DatabaseDetectorResultQuery) Where(ps ...predicate.DatabaseDetectorResult) *DatabaseDetectorResultQuery {
	ddrq.predicates = append(ddrq.predicates, ps...)
	return ddrq
}

// Limit the number of records to be returned by this query.
func (ddrq *DatabaseDetectorResultQuery) Limit(limit int) *DatabaseDetectorResultQuery {
	ddrq.ctx.Limit = &limit
	return ddrq
}

// Offset to start from.
func (ddrq *DatabaseDetectorResultQuery) Offset(offset int) *DatabaseDetectorResultQuery {
	ddrq.ctx.Offset = &offset
	return ddrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ddrq *DatabaseDetectorResultQuery) Unique(unique bool) *DatabaseDetectorResultQuery {
	ddrq.ctx.Unique = &unique
	return ddrq
}

// Order specifies how the records should be ordered.
func (ddrq *DatabaseDetectorResultQuery) Order(o ...databasedetectorresult.OrderOption) *DatabaseDetectorResultQuery {
	ddrq.order = append(ddrq.order, o...)
	return ddrq
}

// First returns the first DatabaseDetectorResult entity from the query.
// Returns a *NotFoundError when no DatabaseDetectorResult was found.
func (ddrq *DatabaseDetectorResultQuery) First(ctx context.Context) (*DatabaseDetectorResult, error) {
	nodes, err := ddrq.Limit(1).All(setContextOp(ctx, ddrq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{databasedetectorresult.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ddrq *DatabaseDetectorResultQuery) FirstX(ctx context.Context) *DatabaseDetectorResult {
	node, err := ddrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DatabaseDetectorResult ID from the query.
// Returns a *NotFoundError when no DatabaseDetectorResult ID was found.
func (ddrq *DatabaseDetectorResultQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ddrq.Limit(1).IDs(setContextOp(ctx, ddrq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{databasedetectorresult.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ddrq *DatabaseDetectorResultQuery) FirstIDX(ctx context.Context) int {
	id, err := ddrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DatabaseDetectorResult entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DatabaseDetectorResult entity is found.
// Returns a *NotFoundError when no DatabaseDetectorResult entities are found.
func (ddrq *DatabaseDetectorResultQuery) Only(ctx context.Context) (*DatabaseDetectorResult, error) {
	nodes, err := ddrq.Limit(2).All(setContextOp(ctx, ddrq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{databasedetectorresult.Label}
	default:
		return nil, &NotSingularError{databasedetectorresult.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ddrq *DatabaseDetectorResultQuery) OnlyX(ctx context.Context) *DatabaseDetectorResult {
	node, err := ddrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DatabaseDetectorResult ID in the query.
// Returns a *NotSingularError when more than one DatabaseDetectorResult ID is found.
// Returns a *NotFoundError when no entities are found.
func (ddrq *DatabaseDetectorResultQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ddrq.Limit(2).IDs(setContextOp(ctx, ddrq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{databasedetectorresult.Label}
	default:
		err = &NotSingularError{databasedetectorresult.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ddrq *DatabaseDetectorResultQuery) OnlyIDX(ctx context.Context) int {
	id, err := ddrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DatabaseDetectorResults.
func (ddrq *DatabaseDetectorResultQuery) All(ctx context.Context) ([]*DatabaseDetectorResult, error) {
	ctx = setContextOp(ctx, ddrq.ctx, "All")
	if err := ddrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DatabaseDetectorResult, *DatabaseDetectorResultQuery]()
	return withInterceptors[[]*DatabaseDetectorResult](ctx, ddrq, qr, ddrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ddrq *DatabaseDetectorResultQuery) AllX(ctx context.Context) []*DatabaseDetectorResult {
	nodes, err := ddrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DatabaseDetectorResult IDs.
func (ddrq *DatabaseDetectorResultQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ddrq.ctx.Unique == nil && ddrq.path != nil {
		ddrq.Unique(true)
	}
	ctx = setContextOp(ctx, ddrq.ctx, "IDs")
	if err = ddrq.Select(databasedetectorresult.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ddrq *DatabaseDetectorResultQuery) IDsX(ctx context.Context) []int {
	ids, err := ddrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ddrq *DatabaseDetectorResultQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ddrq.ctx, "Count")
	if err := ddrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ddrq, querierCount[*DatabaseDetectorResultQuery](), ddrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ddrq *DatabaseDetectorResultQuery) CountX(ctx context.Context) int {
	count, err := ddrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ddrq *DatabaseDetectorResultQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ddrq.ctx, "Exist")
	switch _, err := ddrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ddrq *DatabaseDetectorResultQuery) ExistX(ctx context.Context) bool {
	exist, err := ddrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DatabaseDetectorResultQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ddrq *DatabaseDetectorResultQuery) Clone() *DatabaseDetectorResultQuery {
	if ddrq == nil {
		return nil
	}
	return &DatabaseDetectorResultQuery{
		config:     ddrq.config,
		ctx:        ddrq.ctx.Clone(),
		order:      append([]databasedetectorresult.OrderOption{}, ddrq.order...),
		inters:     append([]Interceptor{}, ddrq.inters...),
		predicates: append([]predicate.DatabaseDetectorResult{}, ddrq.predicates...),
		// clone intermediate query.
		sql:  ddrq.sql.Clone(),
		path: ddrq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt" sql:"created_at"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DatabaseDetectorResult.Query().
//		GroupBy(databasedetectorresult.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ddrq *DatabaseDetectorResultQuery) GroupBy(field string, fields ...string) *DatabaseDetectorResultGroupBy {
	ddrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DatabaseDetectorResultGroupBy{build: ddrq}
	grbuild.flds = &ddrq.ctx.Fields
	grbuild.label = databasedetectorresult.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt" sql:"created_at"`
//	}
//
//	client.DatabaseDetectorResult.Query().
//		Select(databasedetectorresult.FieldCreatedAt).
//		Scan(ctx, &v)
func (ddrq *DatabaseDetectorResultQuery) Select(fields ...string) *DatabaseDetectorResultSelect {
	ddrq.ctx.Fields = append(ddrq.ctx.Fields, fields...)
	sbuild := &DatabaseDetectorResultSelect{DatabaseDetectorResultQuery: ddrq}
	sbuild.label = databasedetectorresult.Label
	sbuild.flds, sbuild.scan = &ddrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DatabaseDetectorResultSelect configured with the given aggregations.
func (ddrq *DatabaseDetectorResultQuery) Aggregate(fns ...AggregateFunc) *DatabaseDetectorResultSelect {
	return ddrq.Select().Aggregate(fns...)
}

func (ddrq *DatabaseDetectorResultQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ddrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ddrq); err != nil {
				return err
			}
		}
	}
	for _, f := range ddrq.ctx.Fields {
		if !databasedetectorresult.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ddrq.path != nil {
		prev, err := ddrq.path(ctx)
		if err != nil {
			return err
		}
		ddrq.sql = prev
	}
	return nil
}

func (ddrq *DatabaseDetectorResultQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DatabaseDetectorResult, error) {
	var (
		nodes = []*DatabaseDetectorResult{}
		_spec = ddrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DatabaseDetectorResult).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DatabaseDetectorResult{config: ddrq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(ddrq.modifiers) > 0 {
		_spec.Modifiers = ddrq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ddrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ddrq *DatabaseDetectorResultQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ddrq.querySpec()
	if len(ddrq.modifiers) > 0 {
		_spec.Modifiers = ddrq.modifiers
	}
	_spec.Node.Columns = ddrq.ctx.Fields
	if len(ddrq.ctx.Fields) > 0 {
		_spec.Unique = ddrq.ctx.Unique != nil && *ddrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ddrq.driver, _spec)
}

func (ddrq *DatabaseDetectorResultQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(databasedetectorresult.Table, databasedetectorresult.Columns, sqlgraph.NewFieldSpec(databasedetectorresult.FieldID, field.TypeInt))
	_spec.From = ddrq.sql
	if unique := ddrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ddrq.path != nil {
		_spec.Unique = true
	}
	if fields := ddrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, databasedetectorresult.FieldID)
		for i := range fields {
			if fields[i] != databasedetectorresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ddrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ddrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ddrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ddrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ddrq *DatabaseDetectorResultQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ddrq.driver.Dialect())
	t1 := builder.Table(databasedetectorresult.Table)
	columns := ddrq.ctx.Fields
	if len(columns) == 0 {
		columns = databasedetectorresult.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ddrq.sql != nil {
		selector = ddrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ddrq.ctx.Unique != nil && *ddrq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range ddrq.modifiers {
		m(selector)
	}
	for _, p := range ddrq.predicates {
		p(selector)
	}
	for _, p := range ddrq.order {
		p(selector)
	}
	if offset := ddrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ddrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ddrq *DatabaseDetectorResultQuery) Modify(modifiers ...func(s *sql.Selector)) *DatabaseDetectorResultSelect {
	ddrq.modifiers = append(ddrq.modifiers, modifiers...)
	return ddrq.Select()
}

// DatabaseDetectorResultGroupBy is the group-by builder for DatabaseDetectorResult entities.
type DatabaseDetectorResultGroupBy struct {
	selector
	build *DatabaseDetectorResultQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ddrgb *DatabaseDetectorResultGroupBy) Aggregate(fns ...AggregateFunc) *DatabaseDetectorResultGroupBy {
	ddrgb.fns = append(ddrgb.fns, fns...)
	return ddrgb
}

// Scan applies the selector query and scans the result into the given value.
func (ddrgb *DatabaseDetectorResultGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ddrgb.build.ctx, "GroupBy")
	if err := ddrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DatabaseDetectorResultQuery, *DatabaseDetectorResultGroupBy](ctx, ddrgb.build, ddrgb, ddrgb.build.inters, v)
}

func (ddrgb *DatabaseDetectorResultGroupBy) sqlScan(ctx context.Context, root *DatabaseDetectorResultQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ddrgb.fns))
	for _, fn := range ddrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ddrgb.flds)+len(ddrgb.fns))
		for _, f := range *ddrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ddrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ddrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DatabaseDetectorResultSelect is the builder for selecting fields of DatabaseDetectorResult entities.
type DatabaseDetectorResultSelect struct {
	*DatabaseDetectorResultQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ddrs *DatabaseDetectorResultSelect) Aggregate(fns ...AggregateFunc) *DatabaseDetectorResultSelect {
	ddrs.fns = append(ddrs.fns, fns...)
	return ddrs
}

// Scan applies the selector query and scans the result into the given value.
func (ddrs *DatabaseDetectorResultSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ddrs.ctx, "Select")
	if err := ddrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DatabaseDetectorResultQuery, *DatabaseDetectorResultSelect](ctx, ddrs.DatabaseDetectorResultQuery, ddrs, ddrs.inters, v)
}

func (ddrs *DatabaseDetectorResultSelect) sqlScan(ctx context.Context, root *DatabaseDetectorResultQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ddrs.fns))
	for _, fn := range ddrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ddrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ddrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ddrs *DatabaseDetectorResultSelect) Modify(modifiers ...func(s *sql.Selector)) *DatabaseDetectorResultSelect {
	ddrs.modifiers = append(ddrs.modifiers, modifiers...)
	return ddrs
}
