// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vicanso/cybertect/ent/dnsdetectorresult"
	"github.com/vicanso/cybertect/ent/predicate"
)

// DNSDetectorResultQuery is the builder for querying DNSDetectorResult entities.
type DNSDetectorResultQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.DNSDetectorResult
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DNSDetectorResultQuery builder.
func (ddrq *DNSDetectorResultQuery) Where(ps ...predicate.DNSDetectorResult) *DNSDetectorResultQuery {
	ddrq.predicates = append(ddrq.predicates, ps...)
	return ddrq
}

// Limit adds a limit step to the query.
func (ddrq *DNSDetectorResultQuery) Limit(limit int) *DNSDetectorResultQuery {
	ddrq.limit = &limit
	return ddrq
}

// Offset adds an offset step to the query.
func (ddrq *DNSDetectorResultQuery) Offset(offset int) *DNSDetectorResultQuery {
	ddrq.offset = &offset
	return ddrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ddrq *DNSDetectorResultQuery) Unique(unique bool) *DNSDetectorResultQuery {
	ddrq.unique = &unique
	return ddrq
}

// Order adds an order step to the query.
func (ddrq *DNSDetectorResultQuery) Order(o ...OrderFunc) *DNSDetectorResultQuery {
	ddrq.order = append(ddrq.order, o...)
	return ddrq
}

// First returns the first DNSDetectorResult entity from the query.
// Returns a *NotFoundError when no DNSDetectorResult was found.
func (ddrq *DNSDetectorResultQuery) First(ctx context.Context) (*DNSDetectorResult, error) {
	nodes, err := ddrq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dnsdetectorresult.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ddrq *DNSDetectorResultQuery) FirstX(ctx context.Context) *DNSDetectorResult {
	node, err := ddrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DNSDetectorResult ID from the query.
// Returns a *NotFoundError when no DNSDetectorResult ID was found.
func (ddrq *DNSDetectorResultQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ddrq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{dnsdetectorresult.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ddrq *DNSDetectorResultQuery) FirstIDX(ctx context.Context) int {
	id, err := ddrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DNSDetectorResult entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DNSDetectorResult entity is found.
// Returns a *NotFoundError when no DNSDetectorResult entities are found.
func (ddrq *DNSDetectorResultQuery) Only(ctx context.Context) (*DNSDetectorResult, error) {
	nodes, err := ddrq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dnsdetectorresult.Label}
	default:
		return nil, &NotSingularError{dnsdetectorresult.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ddrq *DNSDetectorResultQuery) OnlyX(ctx context.Context) *DNSDetectorResult {
	node, err := ddrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DNSDetectorResult ID in the query.
// Returns a *NotSingularError when more than one DNSDetectorResult ID is found.
// Returns a *NotFoundError when no entities are found.
func (ddrq *DNSDetectorResultQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ddrq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{dnsdetectorresult.Label}
	default:
		err = &NotSingularError{dnsdetectorresult.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ddrq *DNSDetectorResultQuery) OnlyIDX(ctx context.Context) int {
	id, err := ddrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DNSDetectorResults.
func (ddrq *DNSDetectorResultQuery) All(ctx context.Context) ([]*DNSDetectorResult, error) {
	if err := ddrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ddrq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ddrq *DNSDetectorResultQuery) AllX(ctx context.Context) []*DNSDetectorResult {
	nodes, err := ddrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DNSDetectorResult IDs.
func (ddrq *DNSDetectorResultQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ddrq.Select(dnsdetectorresult.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ddrq *DNSDetectorResultQuery) IDsX(ctx context.Context) []int {
	ids, err := ddrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ddrq *DNSDetectorResultQuery) Count(ctx context.Context) (int, error) {
	if err := ddrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ddrq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ddrq *DNSDetectorResultQuery) CountX(ctx context.Context) int {
	count, err := ddrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ddrq *DNSDetectorResultQuery) Exist(ctx context.Context) (bool, error) {
	if err := ddrq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ddrq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ddrq *DNSDetectorResultQuery) ExistX(ctx context.Context) bool {
	exist, err := ddrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DNSDetectorResultQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ddrq *DNSDetectorResultQuery) Clone() *DNSDetectorResultQuery {
	if ddrq == nil {
		return nil
	}
	return &DNSDetectorResultQuery{
		config:     ddrq.config,
		limit:      ddrq.limit,
		offset:     ddrq.offset,
		order:      append([]OrderFunc{}, ddrq.order...),
		predicates: append([]predicate.DNSDetectorResult{}, ddrq.predicates...),
		// clone intermediate query.
		sql:    ddrq.sql.Clone(),
		path:   ddrq.path,
		unique: ddrq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt" sql:"created_at"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DNSDetectorResult.Query().
//		GroupBy(dnsdetectorresult.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ddrq *DNSDetectorResultQuery) GroupBy(field string, fields ...string) *DNSDetectorResultGroupBy {
	grbuild := &DNSDetectorResultGroupBy{config: ddrq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ddrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ddrq.sqlQuery(ctx), nil
	}
	grbuild.label = dnsdetectorresult.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt" sql:"created_at"`
//	}
//
//	client.DNSDetectorResult.Query().
//		Select(dnsdetectorresult.FieldCreatedAt).
//		Scan(ctx, &v)
func (ddrq *DNSDetectorResultQuery) Select(fields ...string) *DNSDetectorResultSelect {
	ddrq.fields = append(ddrq.fields, fields...)
	selbuild := &DNSDetectorResultSelect{DNSDetectorResultQuery: ddrq}
	selbuild.label = dnsdetectorresult.Label
	selbuild.flds, selbuild.scan = &ddrq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a DNSDetectorResultSelect configured with the given aggregations.
func (ddrq *DNSDetectorResultQuery) Aggregate(fns ...AggregateFunc) *DNSDetectorResultSelect {
	return ddrq.Select().Aggregate(fns...)
}

func (ddrq *DNSDetectorResultQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ddrq.fields {
		if !dnsdetectorresult.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ddrq.path != nil {
		prev, err := ddrq.path(ctx)
		if err != nil {
			return err
		}
		ddrq.sql = prev
	}
	return nil
}

func (ddrq *DNSDetectorResultQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DNSDetectorResult, error) {
	var (
		nodes = []*DNSDetectorResult{}
		_spec = ddrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DNSDetectorResult).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DNSDetectorResult{config: ddrq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(ddrq.modifiers) > 0 {
		_spec.Modifiers = ddrq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ddrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ddrq *DNSDetectorResultQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ddrq.querySpec()
	if len(ddrq.modifiers) > 0 {
		_spec.Modifiers = ddrq.modifiers
	}
	_spec.Node.Columns = ddrq.fields
	if len(ddrq.fields) > 0 {
		_spec.Unique = ddrq.unique != nil && *ddrq.unique
	}
	return sqlgraph.CountNodes(ctx, ddrq.driver, _spec)
}

func (ddrq *DNSDetectorResultQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := ddrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (ddrq *DNSDetectorResultQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   dnsdetectorresult.Table,
			Columns: dnsdetectorresult.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dnsdetectorresult.FieldID,
			},
		},
		From:   ddrq.sql,
		Unique: true,
	}
	if unique := ddrq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ddrq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dnsdetectorresult.FieldID)
		for i := range fields {
			if fields[i] != dnsdetectorresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ddrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ddrq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ddrq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ddrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ddrq *DNSDetectorResultQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ddrq.driver.Dialect())
	t1 := builder.Table(dnsdetectorresult.Table)
	columns := ddrq.fields
	if len(columns) == 0 {
		columns = dnsdetectorresult.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ddrq.sql != nil {
		selector = ddrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ddrq.unique != nil && *ddrq.unique {
		selector.Distinct()
	}
	for _, m := range ddrq.modifiers {
		m(selector)
	}
	for _, p := range ddrq.predicates {
		p(selector)
	}
	for _, p := range ddrq.order {
		p(selector)
	}
	if offset := ddrq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ddrq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ddrq *DNSDetectorResultQuery) Modify(modifiers ...func(s *sql.Selector)) *DNSDetectorResultSelect {
	ddrq.modifiers = append(ddrq.modifiers, modifiers...)
	return ddrq.Select()
}

// DNSDetectorResultGroupBy is the group-by builder for DNSDetectorResult entities.
type DNSDetectorResultGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ddrgb *DNSDetectorResultGroupBy) Aggregate(fns ...AggregateFunc) *DNSDetectorResultGroupBy {
	ddrgb.fns = append(ddrgb.fns, fns...)
	return ddrgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ddrgb *DNSDetectorResultGroupBy) Scan(ctx context.Context, v any) error {
	query, err := ddrgb.path(ctx)
	if err != nil {
		return err
	}
	ddrgb.sql = query
	return ddrgb.sqlScan(ctx, v)
}

func (ddrgb *DNSDetectorResultGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range ddrgb.fields {
		if !dnsdetectorresult.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ddrgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ddrgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ddrgb *DNSDetectorResultGroupBy) sqlQuery() *sql.Selector {
	selector := ddrgb.sql.Select()
	aggregation := make([]string, 0, len(ddrgb.fns))
	for _, fn := range ddrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ddrgb.fields)+len(ddrgb.fns))
		for _, f := range ddrgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ddrgb.fields...)...)
}

// DNSDetectorResultSelect is the builder for selecting fields of DNSDetectorResult entities.
type DNSDetectorResultSelect struct {
	*DNSDetectorResultQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ddrs *DNSDetectorResultSelect) Aggregate(fns ...AggregateFunc) *DNSDetectorResultSelect {
	ddrs.fns = append(ddrs.fns, fns...)
	return ddrs
}

// Scan applies the selector query and scans the result into the given value.
func (ddrs *DNSDetectorResultSelect) Scan(ctx context.Context, v any) error {
	if err := ddrs.prepareQuery(ctx); err != nil {
		return err
	}
	ddrs.sql = ddrs.DNSDetectorResultQuery.sqlQuery(ctx)
	return ddrs.sqlScan(ctx, v)
}

func (ddrs *DNSDetectorResultSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(ddrs.fns))
	for _, fn := range ddrs.fns {
		aggregation = append(aggregation, fn(ddrs.sql))
	}
	switch n := len(*ddrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		ddrs.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		ddrs.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := ddrs.sql.Query()
	if err := ddrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ddrs *DNSDetectorResultSelect) Modify(modifiers ...func(s *sql.Selector)) *DNSDetectorResultSelect {
	ddrs.modifiers = append(ddrs.modifiers, modifiers...)
	return ddrs
}
