// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vicanso/cybertect/ent/httpdetectorresult"
	"github.com/vicanso/cybertect/ent/predicate"
)

// HTTPDetectorResultQuery is the builder for querying HTTPDetectorResult entities.
type HTTPDetectorResultQuery struct {
	config
	ctx        *QueryContext
	order      []httpdetectorresult.OrderOption
	inters     []Interceptor
	predicates []predicate.HTTPDetectorResult
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HTTPDetectorResultQuery builder.
func (hdrq *HTTPDetectorResultQuery) Where(ps ...predicate.HTTPDetectorResult) *HTTPDetectorResultQuery {
	hdrq.predicates = append(hdrq.predicates, ps...)
	return hdrq
}

// Limit the number of records to be returned by this query.
func (hdrq *HTTPDetectorResultQuery) Limit(limit int) *HTTPDetectorResultQuery {
	hdrq.ctx.Limit = &limit
	return hdrq
}

// Offset to start from.
func (hdrq *HTTPDetectorResultQuery) Offset(offset int) *HTTPDetectorResultQuery {
	hdrq.ctx.Offset = &offset
	return hdrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (hdrq *HTTPDetectorResultQuery) Unique(unique bool) *HTTPDetectorResultQuery {
	hdrq.ctx.Unique = &unique
	return hdrq
}

// Order specifies how the records should be ordered.
func (hdrq *HTTPDetectorResultQuery) Order(o ...httpdetectorresult.OrderOption) *HTTPDetectorResultQuery {
	hdrq.order = append(hdrq.order, o...)
	return hdrq
}

// First returns the first HTTPDetectorResult entity from the query.
// Returns a *NotFoundError when no HTTPDetectorResult was found.
func (hdrq *HTTPDetectorResultQuery) First(ctx context.Context) (*HTTPDetectorResult, error) {
	nodes, err := hdrq.Limit(1).All(setContextOp(ctx, hdrq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{httpdetectorresult.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (hdrq *HTTPDetectorResultQuery) FirstX(ctx context.Context) *HTTPDetectorResult {
	node, err := hdrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HTTPDetectorResult ID from the query.
// Returns a *NotFoundError when no HTTPDetectorResult ID was found.
func (hdrq *HTTPDetectorResultQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = hdrq.Limit(1).IDs(setContextOp(ctx, hdrq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{httpdetectorresult.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (hdrq *HTTPDetectorResultQuery) FirstIDX(ctx context.Context) int {
	id, err := hdrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single HTTPDetectorResult entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one HTTPDetectorResult entity is found.
// Returns a *NotFoundError when no HTTPDetectorResult entities are found.
func (hdrq *HTTPDetectorResultQuery) Only(ctx context.Context) (*HTTPDetectorResult, error) {
	nodes, err := hdrq.Limit(2).All(setContextOp(ctx, hdrq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{httpdetectorresult.Label}
	default:
		return nil, &NotSingularError{httpdetectorresult.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (hdrq *HTTPDetectorResultQuery) OnlyX(ctx context.Context) *HTTPDetectorResult {
	node, err := hdrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only HTTPDetectorResult ID in the query.
// Returns a *NotSingularError when more than one HTTPDetectorResult ID is found.
// Returns a *NotFoundError when no entities are found.
func (hdrq *HTTPDetectorResultQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = hdrq.Limit(2).IDs(setContextOp(ctx, hdrq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{httpdetectorresult.Label}
	default:
		err = &NotSingularError{httpdetectorresult.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (hdrq *HTTPDetectorResultQuery) OnlyIDX(ctx context.Context) int {
	id, err := hdrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HTTPDetectorResults.
func (hdrq *HTTPDetectorResultQuery) All(ctx context.Context) ([]*HTTPDetectorResult, error) {
	ctx = setContextOp(ctx, hdrq.ctx, "All")
	if err := hdrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*HTTPDetectorResult, *HTTPDetectorResultQuery]()
	return withInterceptors[[]*HTTPDetectorResult](ctx, hdrq, qr, hdrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (hdrq *HTTPDetectorResultQuery) AllX(ctx context.Context) []*HTTPDetectorResult {
	nodes, err := hdrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HTTPDetectorResult IDs.
func (hdrq *HTTPDetectorResultQuery) IDs(ctx context.Context) (ids []int, err error) {
	if hdrq.ctx.Unique == nil && hdrq.path != nil {
		hdrq.Unique(true)
	}
	ctx = setContextOp(ctx, hdrq.ctx, "IDs")
	if err = hdrq.Select(httpdetectorresult.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (hdrq *HTTPDetectorResultQuery) IDsX(ctx context.Context) []int {
	ids, err := hdrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (hdrq *HTTPDetectorResultQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, hdrq.ctx, "Count")
	if err := hdrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, hdrq, querierCount[*HTTPDetectorResultQuery](), hdrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (hdrq *HTTPDetectorResultQuery) CountX(ctx context.Context) int {
	count, err := hdrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (hdrq *HTTPDetectorResultQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, hdrq.ctx, "Exist")
	switch _, err := hdrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (hdrq *HTTPDetectorResultQuery) ExistX(ctx context.Context) bool {
	exist, err := hdrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HTTPDetectorResultQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (hdrq *HTTPDetectorResultQuery) Clone() *HTTPDetectorResultQuery {
	if hdrq == nil {
		return nil
	}
	return &HTTPDetectorResultQuery{
		config:     hdrq.config,
		ctx:        hdrq.ctx.Clone(),
		order:      append([]httpdetectorresult.OrderOption{}, hdrq.order...),
		inters:     append([]Interceptor{}, hdrq.inters...),
		predicates: append([]predicate.HTTPDetectorResult{}, hdrq.predicates...),
		// clone intermediate query.
		sql:  hdrq.sql.Clone(),
		path: hdrq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt" sql:"created_at"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HTTPDetectorResult.Query().
//		GroupBy(httpdetectorresult.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (hdrq *HTTPDetectorResultQuery) GroupBy(field string, fields ...string) *HTTPDetectorResultGroupBy {
	hdrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HTTPDetectorResultGroupBy{build: hdrq}
	grbuild.flds = &hdrq.ctx.Fields
	grbuild.label = httpdetectorresult.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt" sql:"created_at"`
//	}
//
//	client.HTTPDetectorResult.Query().
//		Select(httpdetectorresult.FieldCreatedAt).
//		Scan(ctx, &v)
func (hdrq *HTTPDetectorResultQuery) Select(fields ...string) *HTTPDetectorResultSelect {
	hdrq.ctx.Fields = append(hdrq.ctx.Fields, fields...)
	sbuild := &HTTPDetectorResultSelect{HTTPDetectorResultQuery: hdrq}
	sbuild.label = httpdetectorresult.Label
	sbuild.flds, sbuild.scan = &hdrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HTTPDetectorResultSelect configured with the given aggregations.
func (hdrq *HTTPDetectorResultQuery) Aggregate(fns ...AggregateFunc) *HTTPDetectorResultSelect {
	return hdrq.Select().Aggregate(fns...)
}

func (hdrq *HTTPDetectorResultQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range hdrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, hdrq); err != nil {
				return err
			}
		}
	}
	for _, f := range hdrq.ctx.Fields {
		if !httpdetectorresult.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if hdrq.path != nil {
		prev, err := hdrq.path(ctx)
		if err != nil {
			return err
		}
		hdrq.sql = prev
	}
	return nil
}

func (hdrq *HTTPDetectorResultQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*HTTPDetectorResult, error) {
	var (
		nodes = []*HTTPDetectorResult{}
		_spec = hdrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*HTTPDetectorResult).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &HTTPDetectorResult{config: hdrq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(hdrq.modifiers) > 0 {
		_spec.Modifiers = hdrq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, hdrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (hdrq *HTTPDetectorResultQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := hdrq.querySpec()
	if len(hdrq.modifiers) > 0 {
		_spec.Modifiers = hdrq.modifiers
	}
	_spec.Node.Columns = hdrq.ctx.Fields
	if len(hdrq.ctx.Fields) > 0 {
		_spec.Unique = hdrq.ctx.Unique != nil && *hdrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, hdrq.driver, _spec)
}

func (hdrq *HTTPDetectorResultQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(httpdetectorresult.Table, httpdetectorresult.Columns, sqlgraph.NewFieldSpec(httpdetectorresult.FieldID, field.TypeInt))
	_spec.From = hdrq.sql
	if unique := hdrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if hdrq.path != nil {
		_spec.Unique = true
	}
	if fields := hdrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, httpdetectorresult.FieldID)
		for i := range fields {
			if fields[i] != httpdetectorresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := hdrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := hdrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := hdrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := hdrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (hdrq *HTTPDetectorResultQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(hdrq.driver.Dialect())
	t1 := builder.Table(httpdetectorresult.Table)
	columns := hdrq.ctx.Fields
	if len(columns) == 0 {
		columns = httpdetectorresult.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if hdrq.sql != nil {
		selector = hdrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if hdrq.ctx.Unique != nil && *hdrq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range hdrq.modifiers {
		m(selector)
	}
	for _, p := range hdrq.predicates {
		p(selector)
	}
	for _, p := range hdrq.order {
		p(selector)
	}
	if offset := hdrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := hdrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (hdrq *HTTPDetectorResultQuery) Modify(modifiers ...func(s *sql.Selector)) *HTTPDetectorResultSelect {
	hdrq.modifiers = append(hdrq.modifiers, modifiers...)
	return hdrq.Select()
}

// HTTPDetectorResultGroupBy is the group-by builder for HTTPDetectorResult entities.
type HTTPDetectorResultGroupBy struct {
	selector
	build *HTTPDetectorResultQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (hdrgb *HTTPDetectorResultGroupBy) Aggregate(fns ...AggregateFunc) *HTTPDetectorResultGroupBy {
	hdrgb.fns = append(hdrgb.fns, fns...)
	return hdrgb
}

// Scan applies the selector query and scans the result into the given value.
func (hdrgb *HTTPDetectorResultGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hdrgb.build.ctx, "GroupBy")
	if err := hdrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HTTPDetectorResultQuery, *HTTPDetectorResultGroupBy](ctx, hdrgb.build, hdrgb, hdrgb.build.inters, v)
}

func (hdrgb *HTTPDetectorResultGroupBy) sqlScan(ctx context.Context, root *HTTPDetectorResultQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(hdrgb.fns))
	for _, fn := range hdrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*hdrgb.flds)+len(hdrgb.fns))
		for _, f := range *hdrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*hdrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hdrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HTTPDetectorResultSelect is the builder for selecting fields of HTTPDetectorResult entities.
type HTTPDetectorResultSelect struct {
	*HTTPDetectorResultQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (hdrs *HTTPDetectorResultSelect) Aggregate(fns ...AggregateFunc) *HTTPDetectorResultSelect {
	hdrs.fns = append(hdrs.fns, fns...)
	return hdrs
}

// Scan applies the selector query and scans the result into the given value.
func (hdrs *HTTPDetectorResultSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hdrs.ctx, "Select")
	if err := hdrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HTTPDetectorResultQuery, *HTTPDetectorResultSelect](ctx, hdrs.HTTPDetectorResultQuery, hdrs, hdrs.inters, v)
}

func (hdrs *HTTPDetectorResultSelect) sqlScan(ctx context.Context, root *HTTPDetectorResultQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(hdrs.fns))
	for _, fn := range hdrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*hdrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hdrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (hdrs *HTTPDetectorResultSelect) Modify(modifiers ...func(s *sql.Selector)) *HTTPDetectorResultSelect {
	hdrs.modifiers = append(hdrs.modifiers, modifiers...)
	return hdrs
}
