// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vicanso/cybertect/ent/pingdetectorresult"
	"github.com/vicanso/cybertect/schema"
)

// PingDetectorResultCreate is the builder for creating a PingDetectorResult entity.
type PingDetectorResultCreate struct {
	config
	mutation *PingDetectorResultMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (pdrc *PingDetectorResultCreate) SetCreatedAt(t time.Time) *PingDetectorResultCreate {
	pdrc.mutation.SetCreatedAt(t)
	return pdrc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pdrc *PingDetectorResultCreate) SetNillableCreatedAt(t *time.Time) *PingDetectorResultCreate {
	if t != nil {
		pdrc.SetCreatedAt(*t)
	}
	return pdrc
}

// SetUpdatedAt sets the "updated_at" field.
func (pdrc *PingDetectorResultCreate) SetUpdatedAt(t time.Time) *PingDetectorResultCreate {
	pdrc.mutation.SetUpdatedAt(t)
	return pdrc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pdrc *PingDetectorResultCreate) SetNillableUpdatedAt(t *time.Time) *PingDetectorResultCreate {
	if t != nil {
		pdrc.SetUpdatedAt(*t)
	}
	return pdrc
}

// SetTask sets the "task" field.
func (pdrc *PingDetectorResultCreate) SetTask(i int) *PingDetectorResultCreate {
	pdrc.mutation.SetTask(i)
	return pdrc
}

// SetResult sets the "result" field.
func (pdrc *PingDetectorResultCreate) SetResult(sr schema.DetectorResult) *PingDetectorResultCreate {
	pdrc.mutation.SetResult(sr)
	return pdrc
}

// SetMaxDuration sets the "maxDuration" field.
func (pdrc *PingDetectorResultCreate) SetMaxDuration(i int) *PingDetectorResultCreate {
	pdrc.mutation.SetMaxDuration(i)
	return pdrc
}

// SetMessages sets the "messages" field.
func (pdrc *PingDetectorResultCreate) SetMessages(s []string) *PingDetectorResultCreate {
	pdrc.mutation.SetMessages(s)
	return pdrc
}

// SetIps sets the "ips" field.
func (pdrc *PingDetectorResultCreate) SetIps(s []string) *PingDetectorResultCreate {
	pdrc.mutation.SetIps(s)
	return pdrc
}

// SetResults sets the "results" field.
func (pdrc *PingDetectorResultCreate) SetResults(sdsr schema.PingDetectorSubResults) *PingDetectorResultCreate {
	pdrc.mutation.SetResults(sdsr)
	return pdrc
}

// Mutation returns the PingDetectorResultMutation object of the builder.
func (pdrc *PingDetectorResultCreate) Mutation() *PingDetectorResultMutation {
	return pdrc.mutation
}

// Save creates the PingDetectorResult in the database.
func (pdrc *PingDetectorResultCreate) Save(ctx context.Context) (*PingDetectorResult, error) {
	pdrc.defaults()
	return withHooks[*PingDetectorResult, PingDetectorResultMutation](ctx, pdrc.sqlSave, pdrc.mutation, pdrc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pdrc *PingDetectorResultCreate) SaveX(ctx context.Context) *PingDetectorResult {
	v, err := pdrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pdrc *PingDetectorResultCreate) Exec(ctx context.Context) error {
	_, err := pdrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pdrc *PingDetectorResultCreate) ExecX(ctx context.Context) {
	if err := pdrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pdrc *PingDetectorResultCreate) defaults() {
	if _, ok := pdrc.mutation.CreatedAt(); !ok {
		v := pingdetectorresult.DefaultCreatedAt()
		pdrc.mutation.SetCreatedAt(v)
	}
	if _, ok := pdrc.mutation.UpdatedAt(); !ok {
		v := pingdetectorresult.DefaultUpdatedAt()
		pdrc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pdrc *PingDetectorResultCreate) check() error {
	if _, ok := pdrc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PingDetectorResult.created_at"`)}
	}
	if _, ok := pdrc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PingDetectorResult.updated_at"`)}
	}
	if _, ok := pdrc.mutation.Task(); !ok {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required field "PingDetectorResult.task"`)}
	}
	if _, ok := pdrc.mutation.Result(); !ok {
		return &ValidationError{Name: "result", err: errors.New(`ent: missing required field "PingDetectorResult.result"`)}
	}
	if v, ok := pdrc.mutation.Result(); ok {
		if err := pingdetectorresult.ResultValidator(int8(v)); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "PingDetectorResult.result": %w`, err)}
		}
	}
	if _, ok := pdrc.mutation.MaxDuration(); !ok {
		return &ValidationError{Name: "maxDuration", err: errors.New(`ent: missing required field "PingDetectorResult.maxDuration"`)}
	}
	if _, ok := pdrc.mutation.Messages(); !ok {
		return &ValidationError{Name: "messages", err: errors.New(`ent: missing required field "PingDetectorResult.messages"`)}
	}
	if _, ok := pdrc.mutation.Ips(); !ok {
		return &ValidationError{Name: "ips", err: errors.New(`ent: missing required field "PingDetectorResult.ips"`)}
	}
	if _, ok := pdrc.mutation.Results(); !ok {
		return &ValidationError{Name: "results", err: errors.New(`ent: missing required field "PingDetectorResult.results"`)}
	}
	return nil
}

func (pdrc *PingDetectorResultCreate) sqlSave(ctx context.Context) (*PingDetectorResult, error) {
	if err := pdrc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pdrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pdrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pdrc.mutation.id = &_node.ID
	pdrc.mutation.done = true
	return _node, nil
}

func (pdrc *PingDetectorResultCreate) createSpec() (*PingDetectorResult, *sqlgraph.CreateSpec) {
	var (
		_node = &PingDetectorResult{config: pdrc.config}
		_spec = sqlgraph.NewCreateSpec(pingdetectorresult.Table, sqlgraph.NewFieldSpec(pingdetectorresult.FieldID, field.TypeInt))
	)
	if value, ok := pdrc.mutation.CreatedAt(); ok {
		_spec.SetField(pingdetectorresult.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pdrc.mutation.UpdatedAt(); ok {
		_spec.SetField(pingdetectorresult.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := pdrc.mutation.Task(); ok {
		_spec.SetField(pingdetectorresult.FieldTask, field.TypeInt, value)
		_node.Task = value
	}
	if value, ok := pdrc.mutation.Result(); ok {
		_spec.SetField(pingdetectorresult.FieldResult, field.TypeInt8, value)
		_node.Result = value
	}
	if value, ok := pdrc.mutation.MaxDuration(); ok {
		_spec.SetField(pingdetectorresult.FieldMaxDuration, field.TypeInt, value)
		_node.MaxDuration = value
	}
	if value, ok := pdrc.mutation.Messages(); ok {
		_spec.SetField(pingdetectorresult.FieldMessages, field.TypeJSON, value)
		_node.Messages = value
	}
	if value, ok := pdrc.mutation.Ips(); ok {
		_spec.SetField(pingdetectorresult.FieldIps, field.TypeJSON, value)
		_node.Ips = value
	}
	if value, ok := pdrc.mutation.Results(); ok {
		_spec.SetField(pingdetectorresult.FieldResults, field.TypeJSON, value)
		_node.Results = value
	}
	return _node, _spec
}

// PingDetectorResultCreateBulk is the builder for creating many PingDetectorResult entities in bulk.
type PingDetectorResultCreateBulk struct {
	config
	builders []*PingDetectorResultCreate
}

// Save creates the PingDetectorResult entities in the database.
func (pdrcb *PingDetectorResultCreateBulk) Save(ctx context.Context) ([]*PingDetectorResult, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pdrcb.builders))
	nodes := make([]*PingDetectorResult, len(pdrcb.builders))
	mutators := make([]Mutator, len(pdrcb.builders))
	for i := range pdrcb.builders {
		func(i int, root context.Context) {
			builder := pdrcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PingDetectorResultMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pdrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pdrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pdrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pdrcb *PingDetectorResultCreateBulk) SaveX(ctx context.Context) []*PingDetectorResult {
	v, err := pdrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pdrcb *PingDetectorResultCreateBulk) Exec(ctx context.Context) error {
	_, err := pdrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pdrcb *PingDetectorResultCreateBulk) ExecX(ctx context.Context) {
	if err := pdrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
