// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vicanso/cybertect/ent/pingdetector"
	"github.com/vicanso/cybertect/ent/predicate"
)

// PingDetectorQuery is the builder for querying PingDetector entities.
type PingDetectorQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.PingDetector
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PingDetectorQuery builder.
func (pdq *PingDetectorQuery) Where(ps ...predicate.PingDetector) *PingDetectorQuery {
	pdq.predicates = append(pdq.predicates, ps...)
	return pdq
}

// Limit adds a limit step to the query.
func (pdq *PingDetectorQuery) Limit(limit int) *PingDetectorQuery {
	pdq.limit = &limit
	return pdq
}

// Offset adds an offset step to the query.
func (pdq *PingDetectorQuery) Offset(offset int) *PingDetectorQuery {
	pdq.offset = &offset
	return pdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pdq *PingDetectorQuery) Unique(unique bool) *PingDetectorQuery {
	pdq.unique = &unique
	return pdq
}

// Order adds an order step to the query.
func (pdq *PingDetectorQuery) Order(o ...OrderFunc) *PingDetectorQuery {
	pdq.order = append(pdq.order, o...)
	return pdq
}

// First returns the first PingDetector entity from the query.
// Returns a *NotFoundError when no PingDetector was found.
func (pdq *PingDetectorQuery) First(ctx context.Context) (*PingDetector, error) {
	nodes, err := pdq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pingdetector.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pdq *PingDetectorQuery) FirstX(ctx context.Context) *PingDetector {
	node, err := pdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PingDetector ID from the query.
// Returns a *NotFoundError when no PingDetector ID was found.
func (pdq *PingDetectorQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pdq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pingdetector.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pdq *PingDetectorQuery) FirstIDX(ctx context.Context) int {
	id, err := pdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PingDetector entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PingDetector entity is found.
// Returns a *NotFoundError when no PingDetector entities are found.
func (pdq *PingDetectorQuery) Only(ctx context.Context) (*PingDetector, error) {
	nodes, err := pdq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pingdetector.Label}
	default:
		return nil, &NotSingularError{pingdetector.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pdq *PingDetectorQuery) OnlyX(ctx context.Context) *PingDetector {
	node, err := pdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PingDetector ID in the query.
// Returns a *NotSingularError when more than one PingDetector ID is found.
// Returns a *NotFoundError when no entities are found.
func (pdq *PingDetectorQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pdq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pingdetector.Label}
	default:
		err = &NotSingularError{pingdetector.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pdq *PingDetectorQuery) OnlyIDX(ctx context.Context) int {
	id, err := pdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PingDetectors.
func (pdq *PingDetectorQuery) All(ctx context.Context) ([]*PingDetector, error) {
	if err := pdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return pdq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (pdq *PingDetectorQuery) AllX(ctx context.Context) []*PingDetector {
	nodes, err := pdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PingDetector IDs.
func (pdq *PingDetectorQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := pdq.Select(pingdetector.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pdq *PingDetectorQuery) IDsX(ctx context.Context) []int {
	ids, err := pdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pdq *PingDetectorQuery) Count(ctx context.Context) (int, error) {
	if err := pdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return pdq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (pdq *PingDetectorQuery) CountX(ctx context.Context) int {
	count, err := pdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pdq *PingDetectorQuery) Exist(ctx context.Context) (bool, error) {
	if err := pdq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return pdq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (pdq *PingDetectorQuery) ExistX(ctx context.Context) bool {
	exist, err := pdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PingDetectorQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pdq *PingDetectorQuery) Clone() *PingDetectorQuery {
	if pdq == nil {
		return nil
	}
	return &PingDetectorQuery{
		config:     pdq.config,
		limit:      pdq.limit,
		offset:     pdq.offset,
		order:      append([]OrderFunc{}, pdq.order...),
		predicates: append([]predicate.PingDetector{}, pdq.predicates...),
		// clone intermediate query.
		sql:    pdq.sql.Clone(),
		path:   pdq.path,
		unique: pdq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt" sql:"created_at"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PingDetector.Query().
//		GroupBy(pingdetector.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pdq *PingDetectorQuery) GroupBy(field string, fields ...string) *PingDetectorGroupBy {
	grbuild := &PingDetectorGroupBy{config: pdq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := pdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return pdq.sqlQuery(ctx), nil
	}
	grbuild.label = pingdetector.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt" sql:"created_at"`
//	}
//
//	client.PingDetector.Query().
//		Select(pingdetector.FieldCreatedAt).
//		Scan(ctx, &v)
func (pdq *PingDetectorQuery) Select(fields ...string) *PingDetectorSelect {
	pdq.fields = append(pdq.fields, fields...)
	selbuild := &PingDetectorSelect{PingDetectorQuery: pdq}
	selbuild.label = pingdetector.Label
	selbuild.flds, selbuild.scan = &pdq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a PingDetectorSelect configured with the given aggregations.
func (pdq *PingDetectorQuery) Aggregate(fns ...AggregateFunc) *PingDetectorSelect {
	return pdq.Select().Aggregate(fns...)
}

func (pdq *PingDetectorQuery) prepareQuery(ctx context.Context) error {
	for _, f := range pdq.fields {
		if !pingdetector.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pdq.path != nil {
		prev, err := pdq.path(ctx)
		if err != nil {
			return err
		}
		pdq.sql = prev
	}
	return nil
}

func (pdq *PingDetectorQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PingDetector, error) {
	var (
		nodes = []*PingDetector{}
		_spec = pdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PingDetector).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PingDetector{config: pdq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(pdq.modifiers) > 0 {
		_spec.Modifiers = pdq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pdq *PingDetectorQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pdq.querySpec()
	if len(pdq.modifiers) > 0 {
		_spec.Modifiers = pdq.modifiers
	}
	_spec.Node.Columns = pdq.fields
	if len(pdq.fields) > 0 {
		_spec.Unique = pdq.unique != nil && *pdq.unique
	}
	return sqlgraph.CountNodes(ctx, pdq.driver, _spec)
}

func (pdq *PingDetectorQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := pdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (pdq *PingDetectorQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   pingdetector.Table,
			Columns: pingdetector.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pingdetector.FieldID,
			},
		},
		From:   pdq.sql,
		Unique: true,
	}
	if unique := pdq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := pdq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pingdetector.FieldID)
		for i := range fields {
			if fields[i] != pingdetector.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pdq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pdq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pdq *PingDetectorQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pdq.driver.Dialect())
	t1 := builder.Table(pingdetector.Table)
	columns := pdq.fields
	if len(columns) == 0 {
		columns = pingdetector.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pdq.sql != nil {
		selector = pdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pdq.unique != nil && *pdq.unique {
		selector.Distinct()
	}
	for _, m := range pdq.modifiers {
		m(selector)
	}
	for _, p := range pdq.predicates {
		p(selector)
	}
	for _, p := range pdq.order {
		p(selector)
	}
	if offset := pdq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pdq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (pdq *PingDetectorQuery) Modify(modifiers ...func(s *sql.Selector)) *PingDetectorSelect {
	pdq.modifiers = append(pdq.modifiers, modifiers...)
	return pdq.Select()
}

// PingDetectorGroupBy is the group-by builder for PingDetector entities.
type PingDetectorGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pdgb *PingDetectorGroupBy) Aggregate(fns ...AggregateFunc) *PingDetectorGroupBy {
	pdgb.fns = append(pdgb.fns, fns...)
	return pdgb
}

// Scan applies the group-by query and scans the result into the given value.
func (pdgb *PingDetectorGroupBy) Scan(ctx context.Context, v any) error {
	query, err := pdgb.path(ctx)
	if err != nil {
		return err
	}
	pdgb.sql = query
	return pdgb.sqlScan(ctx, v)
}

func (pdgb *PingDetectorGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range pdgb.fields {
		if !pingdetector.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pdgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pdgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pdgb *PingDetectorGroupBy) sqlQuery() *sql.Selector {
	selector := pdgb.sql.Select()
	aggregation := make([]string, 0, len(pdgb.fns))
	for _, fn := range pdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(pdgb.fields)+len(pdgb.fns))
		for _, f := range pdgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(pdgb.fields...)...)
}

// PingDetectorSelect is the builder for selecting fields of PingDetector entities.
type PingDetectorSelect struct {
	*PingDetectorQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pds *PingDetectorSelect) Aggregate(fns ...AggregateFunc) *PingDetectorSelect {
	pds.fns = append(pds.fns, fns...)
	return pds
}

// Scan applies the selector query and scans the result into the given value.
func (pds *PingDetectorSelect) Scan(ctx context.Context, v any) error {
	if err := pds.prepareQuery(ctx); err != nil {
		return err
	}
	pds.sql = pds.PingDetectorQuery.sqlQuery(ctx)
	return pds.sqlScan(ctx, v)
}

func (pds *PingDetectorSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(pds.fns))
	for _, fn := range pds.fns {
		aggregation = append(aggregation, fn(pds.sql))
	}
	switch n := len(*pds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		pds.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		pds.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := pds.sql.Query()
	if err := pds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (pds *PingDetectorSelect) Modify(modifiers ...func(s *sql.Selector)) *PingDetectorSelect {
	pds.modifiers = append(pds.modifiers, modifiers...)
	return pds
}
