// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/vicanso/cybertect/ent/pingdetectorresult"
	"github.com/vicanso/cybertect/ent/predicate"
)

// PingDetectorResultDelete is the builder for deleting a PingDetectorResult entity.
type PingDetectorResultDelete struct {
	config
	hooks    []Hook
	mutation *PingDetectorResultMutation
}

// Where adds a new predicate to the PingDetectorResultDelete builder.
func (pdrd *PingDetectorResultDelete) Where(ps ...predicate.PingDetectorResult) *PingDetectorResultDelete {
	pdrd.mutation.predicates = append(pdrd.mutation.predicates, ps...)
	return pdrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pdrd *PingDetectorResultDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pdrd.hooks) == 0 {
		affected, err = pdrd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PingDetectorResultMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pdrd.mutation = mutation
			affected, err = pdrd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pdrd.hooks) - 1; i >= 0; i-- {
			mut = pdrd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pdrd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pdrd *PingDetectorResultDelete) ExecX(ctx context.Context) int {
	n, err := pdrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pdrd *PingDetectorResultDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: pingdetectorresult.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pingdetectorresult.FieldID,
			},
		},
	}
	if ps := pdrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pdrd.driver, _spec)
}

// PingDetectorResultDeleteOne is the builder for deleting a single PingDetectorResult entity.
type PingDetectorResultDeleteOne struct {
	pdrd *PingDetectorResultDelete
}

// Exec executes the deletion query.
func (pdrdo *PingDetectorResultDeleteOne) Exec(ctx context.Context) error {
	n, err := pdrdo.pdrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pingdetectorresult.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pdrdo *PingDetectorResultDeleteOne) ExecX(ctx context.Context) {
	pdrdo.pdrd.ExecX(ctx)
}
