// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/vicanso/cybertect/ent/pingdetector"
	"github.com/vicanso/cybertect/ent/schema"
)

// PingDetectorCreate is the builder for creating a PingDetector entity.
type PingDetectorCreate struct {
	config
	mutation *PingDetectorMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (pdc *PingDetectorCreate) SetCreatedAt(t time.Time) *PingDetectorCreate {
	pdc.mutation.SetCreatedAt(t)
	return pdc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pdc *PingDetectorCreate) SetNillableCreatedAt(t *time.Time) *PingDetectorCreate {
	if t != nil {
		pdc.SetCreatedAt(*t)
	}
	return pdc
}

// SetUpdatedAt sets the "updated_at" field.
func (pdc *PingDetectorCreate) SetUpdatedAt(t time.Time) *PingDetectorCreate {
	pdc.mutation.SetUpdatedAt(t)
	return pdc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pdc *PingDetectorCreate) SetNillableUpdatedAt(t *time.Time) *PingDetectorCreate {
	if t != nil {
		pdc.SetUpdatedAt(*t)
	}
	return pdc
}

// SetStatus sets the "status" field.
func (pdc *PingDetectorCreate) SetStatus(s schema.Status) *PingDetectorCreate {
	pdc.mutation.SetStatus(s)
	return pdc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pdc *PingDetectorCreate) SetNillableStatus(s *schema.Status) *PingDetectorCreate {
	if s != nil {
		pdc.SetStatus(*s)
	}
	return pdc
}

// SetName sets the "name" field.
func (pdc *PingDetectorCreate) SetName(s string) *PingDetectorCreate {
	pdc.mutation.SetName(s)
	return pdc
}

// SetOwner sets the "owner" field.
func (pdc *PingDetectorCreate) SetOwner(s string) *PingDetectorCreate {
	pdc.mutation.SetOwner(s)
	return pdc
}

// SetDescription sets the "description" field.
func (pdc *PingDetectorCreate) SetDescription(s string) *PingDetectorCreate {
	pdc.mutation.SetDescription(s)
	return pdc
}

// SetReceivers sets the "receivers" field.
func (pdc *PingDetectorCreate) SetReceivers(s []string) *PingDetectorCreate {
	pdc.mutation.SetReceivers(s)
	return pdc
}

// SetTimeout sets the "timeout" field.
func (pdc *PingDetectorCreate) SetTimeout(s string) *PingDetectorCreate {
	pdc.mutation.SetTimeout(s)
	return pdc
}

// SetIps sets the "ips" field.
func (pdc *PingDetectorCreate) SetIps(s []string) *PingDetectorCreate {
	pdc.mutation.SetIps(s)
	return pdc
}

// Mutation returns the PingDetectorMutation object of the builder.
func (pdc *PingDetectorCreate) Mutation() *PingDetectorMutation {
	return pdc.mutation
}

// Save creates the PingDetector in the database.
func (pdc *PingDetectorCreate) Save(ctx context.Context) (*PingDetector, error) {
	var (
		err  error
		node *PingDetector
	)
	pdc.defaults()
	if len(pdc.hooks) == 0 {
		if err = pdc.check(); err != nil {
			return nil, err
		}
		node, err = pdc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PingDetectorMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pdc.check(); err != nil {
				return nil, err
			}
			pdc.mutation = mutation
			node, err = pdc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pdc.hooks) - 1; i >= 0; i-- {
			mut = pdc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pdc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pdc *PingDetectorCreate) SaveX(ctx context.Context) *PingDetector {
	v, err := pdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (pdc *PingDetectorCreate) defaults() {
	if _, ok := pdc.mutation.CreatedAt(); !ok {
		v := pingdetector.DefaultCreatedAt()
		pdc.mutation.SetCreatedAt(v)
	}
	if _, ok := pdc.mutation.UpdatedAt(); !ok {
		v := pingdetector.DefaultUpdatedAt()
		pdc.mutation.SetUpdatedAt(v)
	}
	if _, ok := pdc.mutation.Status(); !ok {
		v := pingdetector.DefaultStatus
		pdc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pdc *PingDetectorCreate) check() error {
	if _, ok := pdc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New("ent: missing required field \"created_at\"")}
	}
	if _, ok := pdc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New("ent: missing required field \"updated_at\"")}
	}
	if _, ok := pdc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New("ent: missing required field \"status\"")}
	}
	if v, ok := pdc.mutation.Status(); ok {
		if err := pingdetector.StatusValidator(int8(v)); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf("ent: validator failed for field \"status\": %w", err)}
		}
	}
	if _, ok := pdc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if v, ok := pdc.mutation.Name(); ok {
		if err := pingdetector.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	if _, ok := pdc.mutation.Owner(); !ok {
		return &ValidationError{Name: "owner", err: errors.New("ent: missing required field \"owner\"")}
	}
	if v, ok := pdc.mutation.Owner(); ok {
		if err := pingdetector.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf("ent: validator failed for field \"owner\": %w", err)}
		}
	}
	if _, ok := pdc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New("ent: missing required field \"description\"")}
	}
	if _, ok := pdc.mutation.Receivers(); !ok {
		return &ValidationError{Name: "receivers", err: errors.New("ent: missing required field \"receivers\"")}
	}
	if _, ok := pdc.mutation.Timeout(); !ok {
		return &ValidationError{Name: "timeout", err: errors.New("ent: missing required field \"timeout\"")}
	}
	if v, ok := pdc.mutation.Timeout(); ok {
		if err := pingdetector.TimeoutValidator(v); err != nil {
			return &ValidationError{Name: "timeout", err: fmt.Errorf("ent: validator failed for field \"timeout\": %w", err)}
		}
	}
	if _, ok := pdc.mutation.Ips(); !ok {
		return &ValidationError{Name: "ips", err: errors.New("ent: missing required field \"ips\"")}
	}
	return nil
}

func (pdc *PingDetectorCreate) sqlSave(ctx context.Context) (*PingDetector, error) {
	_node, _spec := pdc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pdc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (pdc *PingDetectorCreate) createSpec() (*PingDetector, *sqlgraph.CreateSpec) {
	var (
		_node = &PingDetector{config: pdc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: pingdetector.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pingdetector.FieldID,
			},
		}
	)
	if value, ok := pdc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: pingdetector.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := pdc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: pingdetector.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := pdc.mutation.Status(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: pingdetector.FieldStatus,
		})
		_node.Status = value
	}
	if value, ok := pdc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: pingdetector.FieldName,
		})
		_node.Name = value
	}
	if value, ok := pdc.mutation.Owner(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: pingdetector.FieldOwner,
		})
		_node.Owner = value
	}
	if value, ok := pdc.mutation.Description(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: pingdetector.FieldDescription,
		})
		_node.Description = value
	}
	if value, ok := pdc.mutation.Receivers(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: pingdetector.FieldReceivers,
		})
		_node.Receivers = value
	}
	if value, ok := pdc.mutation.Timeout(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: pingdetector.FieldTimeout,
		})
		_node.Timeout = value
	}
	if value, ok := pdc.mutation.Ips(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: pingdetector.FieldIps,
		})
		_node.Ips = value
	}
	return _node, _spec
}

// PingDetectorCreateBulk is the builder for creating many PingDetector entities in bulk.
type PingDetectorCreateBulk struct {
	config
	builders []*PingDetectorCreate
}

// Save creates the PingDetector entities in the database.
func (pdcb *PingDetectorCreateBulk) Save(ctx context.Context) ([]*PingDetector, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pdcb.builders))
	nodes := make([]*PingDetector, len(pdcb.builders))
	mutators := make([]Mutator, len(pdcb.builders))
	for i := range pdcb.builders {
		func(i int, root context.Context) {
			builder := pdcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PingDetectorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pdcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pdcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pdcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pdcb *PingDetectorCreateBulk) SaveX(ctx context.Context) []*PingDetector {
	v, err := pdcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
