# 系统基本配置
basic:
  name: cybertect
  # 系统并发限制
  requestLimit: 1000
  listen: :7001
  # 如果需要支持前缀，则可添加配置
  # prefixes:
  # - /api

# 用户session的配置
session:
  path: /
  key: cybertect
  # 5天
  ttl: 120h
  # 用于加密session cookie 
  secret: SECRET
  trackKey: jt

# postgres postgres配置
postgres:
  # 可以配置为下面的形式，则从env中获取POSTGRES_URI对应的字符串来当postgres连接串
  # uri: POSTGRES_URI
  uri: postgresql://vicanso:A123456@127.0.0.1:5432/cybertect

# influxdb 配置
influxdb:
  uri: http://127.0.0.1:8086
  bucket: cybertect 
  org: bigTree
  token: YXFOYqPAxtF2wxfVMn-M168Y8rbAFhOsMDKCVWaStmEtFTqFX9KtcYDQk5ouwCNJY0iyW1KVE-VhmmAAhnfG5w==
  batchSize: 100
  flushInterval: 10s
  # 如果与influxdb非同一内网，建议设置为true
  gzip: false
  disabled: true 

# mail相关配置
mail:
  host: MAIL_HOST 
  port: MAIL_PORT
  user: MAIL_USER
  password: MAIL_PASS

# 告警接收邮件列表
alarm:
  receivers:
  # - tree.xie@outlook.com

# 定位相关配置
location:
  name: location
  timeout: 3s
  baseURL: https://ip.npmtrend.com

# minio配置
minio:
  endpoint: 127.0.0.1:9000
  accessKeyID: origin 
  secretAccessKey: test123456
  ssl: false

detector:
  interval: DETECTOR_INTERVAL
  concurrency: 5