name: Build 

on:
  push:
    tags:
      - 'v*.*.*'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: make build-web

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Get dependencies
      run: 
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest

    - name: Install
      run: make install

    - name: Generate
      run: make generate
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}