name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:alpine
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cybertect
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:

    - name: cybertect test 
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.4

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    
    - name: Get dependencies
      run: 
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.53.1

    - name: Install
      run: make install

    - name: Generate
      run: make generate

    - name: Lint
      run: make lint

    - name: Test
      run: make test
      env:
        GO_ENV: test
        POSTGRES_URI: postgresql://postgres:postgres@127.0.0.1:5432/postgres

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64, linux/arm64, linux/arm/v7
        push: true
        tags: vicanso/cybertect
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}